### ISSUE TITLE
a href doesn't work properly

### ISSUE THREAD

**Issue by kiprasmel** [adam-lynch/adam-lynch.github.io#6]
Hey there, nice blog, love reading it!

I came across https://adamlynch.com/random-open-api/#conclusion, and tried clicking on `@randomOpenAPI` and `github.com/adam-lynch/random-open-api`.

They don't redirect to the url you're expecting them to.

| Currently redirects | Should redirect |
----------------------|------------------
https://adamlynch.com/random-open-api/twitter.com/randomOpenAPI | https://twitter.com/randomOpenAPI
https://adamlynch.com/random-open-api/github.com/adam-lynch/random-open-api | https://github.com/adam-lynch/random-open-api

---

I managed to quickly fix the `<a href="">` by prefixing the url with two slashes `//` like so:

from
`<a href="twitter.com/randomOpenAPI` to
`<a href="//twitter.com/randomOpenAPI`

And, obviously, this redirection error applies to the whole site I suppose, unless you've done something somewhere differently.

I don't know if this is fully compatible, so you should probably do some research yourself. I'd be interested to know about what you decide to use:)

**Comment by adam-lynch** [comment]
Wow, I have no idea how I missed this for 3 years! How embarrassing. Anyway, I've fixed it now. Thanks

**Comment by kiprasmel** [comment]
lol, cheers
